[2023-07-09T19:48:52.809+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: segmentacao_agv_tim.executa_consultas_agv manual__2023-07-09T19:48:51.514647+00:00 [queued]>
[2023-07-09T19:48:52.824+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: segmentacao_agv_tim.executa_consultas_agv manual__2023-07-09T19:48:51.514647+00:00 [queued]>
[2023-07-09T19:48:52.825+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-09T19:48:52.848+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): executa_consultas_agv> on 2023-07-09 19:48:51.514647+00:00
[2023-07-09T19:48:52.856+0000] {standard_task_runner.py:57} INFO - Started process 77 to run task
[2023-07-09T19:48:52.861+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'segmentacao_agv_tim', 'executa_consultas_agv', 'manual__2023-07-09T19:48:51.514647+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/segmentacao_tim/dag_agv_tim.py', '--cfg-path', '/tmp/tmps0djmvsq']
[2023-07-09T19:48:52.862+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask executa_consultas_agv
[2023-07-09T19:48:52.926+0000] {task_command.py:410} INFO - Running <TaskInstance: segmentacao_agv_tim.executa_consultas_agv manual__2023-07-09T19:48:51.514647+00:00 [running]> on host 17547dfb54ad
[2023-07-09T19:48:53.053+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='segmentacao_agv_tim' AIRFLOW_CTX_TASK_ID='executa_consultas_agv' AIRFLOW_CTX_EXECUTION_DATE='2023-07-09T19:48:51.514647+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-09T19:48:51.514647+00:00'
[2023-07-09T19:48:53.073+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/segmentacao_tim/dag_agv_tim.py", line 42, in get_segmentacao_agv_tim
    order_summary = transform(order_data)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 345, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    self.set_xcomargs_dependencies()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1173, in set_xcomargs_dependencies
    XComArg.apply_upstream_relationship(self, arg)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom_arg.py", line 124, in apply_upstream_relationship
    op.set_upstream(operator)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskmixin.py", line 237, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskmixin.py", line 200, in _set_relatives
    f"Tried to create relationships between tasks that don't have DAGs yet. "
airflow.exceptions.AirflowException: Tried to create relationships between tasks that don't have DAGs yet. Set the DAG for at least one task and try again: [<Task(_PythonDecoratedOperator): transform>, <Task(_PythonDecoratedOperator): extract>]
[2023-07-09T19:48:53.080+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=segmentacao_agv_tim, task_id=executa_consultas_agv, execution_date=20230709T194851, start_date=20230709T194852, end_date=20230709T194853
[2023-07-09T19:48:53.096+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 24 for task executa_consultas_agv (Tried to create relationships between tasks that don't have DAGs yet. Set the DAG for at least one task and try again: [<Task(_PythonDecoratedOperator): transform>, <Task(_PythonDecoratedOperator): extract>]; 77)
[2023-07-09T19:48:53.112+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-09T19:48:53.134+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
